### ISSUE TITLE
Fix crashing

### ISSUE THREAD

**Issue by dordzhiev** [AOSP-11/device_xiaomi_sagit#1]
I don’t know where to write, but because of you don’t visit the telegram chat, I’m leaving it here
https://review.lineageos.org/c/LineageOS/android_packages_apps_Settings/+/305653

**Comment by sbwml** [comment]
我目前已经没有小米6设备，我不知道当前AOSP-11 的状况如何，如果你遇到的问题可以使用上面提供的commit 进行修复，我可以将其合并到源码当中。在下一次构建时会应用它 https://github.com/AOSP-11/packages_apps_Settings/commit/56e536b84a444385d02429841d96def17d8b1232
